// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timesheet.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TSStatusResponse_Status int32

const (
	TSStatusResponse_ClockedOut TSStatusResponse_Status = 0
	TSStatusResponse_ClockedIn  TSStatusResponse_Status = 1
)

var TSStatusResponse_Status_name = map[int32]string{
	0: "ClockedOut",
	1: "ClockedIn",
}
var TSStatusResponse_Status_value = map[string]int32{
	"ClockedOut": 0,
	"ClockedIn":  1,
}

func (x TSStatusResponse_Status) String() string {
	return proto.EnumName(TSStatusResponse_Status_name, int32(x))
}
func (TSStatusResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type TimeEntry_Status int32

const (
	TimeEntry_ClockedOut TimeEntry_Status = 0
	TimeEntry_ClockedIn  TimeEntry_Status = 1
)

var TimeEntry_Status_name = map[int32]string{
	0: "ClockedOut",
	1: "ClockedIn",
}
var TimeEntry_Status_value = map[string]int32{
	"ClockedOut": 0,
	"ClockedIn":  1,
}

func (x TimeEntry_Status) String() string {
	return proto.EnumName(TimeEntry_Status_name, int32(x))
}
func (TimeEntry_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

type ClockRequest struct {
}

func (m *ClockRequest) Reset()                    { *m = ClockRequest{} }
func (m *ClockRequest) String() string            { return proto.CompactTextString(m) }
func (*ClockRequest) ProtoMessage()               {}
func (*ClockRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type TimeSheetRequest struct {
	Options   *SearchOptions             `protobuf:"bytes,1,opt,name=Options" json:"Options,omitempty"`
	StartTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime   *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=EndTime" json:"EndTime,omitempty"`
	// Types that are valid to be assigned to UserIdent:
	//	*TimeSheetRequest_Email
	//	*TimeSheetRequest_UserID
	UserIdent isTimeSheetRequest_UserIdent `protobuf_oneof:"UserIdent"`
}

func (m *TimeSheetRequest) Reset()                    { *m = TimeSheetRequest{} }
func (m *TimeSheetRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeSheetRequest) ProtoMessage()               {}
func (*TimeSheetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isTimeSheetRequest_UserIdent interface {
	isTimeSheetRequest_UserIdent()
}

type TimeSheetRequest_Email struct {
	Email string `protobuf:"bytes,4,opt,name=Email,oneof"`
}
type TimeSheetRequest_UserID struct {
	UserID int64 `protobuf:"varint,5,opt,name=UserID,oneof"`
}

func (*TimeSheetRequest_Email) isTimeSheetRequest_UserIdent()  {}
func (*TimeSheetRequest_UserID) isTimeSheetRequest_UserIdent() {}

func (m *TimeSheetRequest) GetUserIdent() isTimeSheetRequest_UserIdent {
	if m != nil {
		return m.UserIdent
	}
	return nil
}

func (m *TimeSheetRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *TimeSheetRequest) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TimeSheetRequest) GetEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TimeSheetRequest) GetEmail() string {
	if x, ok := m.GetUserIdent().(*TimeSheetRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (m *TimeSheetRequest) GetUserID() int64 {
	if x, ok := m.GetUserIdent().(*TimeSheetRequest_UserID); ok {
		return x.UserID
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TimeSheetRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TimeSheetRequest_OneofMarshaler, _TimeSheetRequest_OneofUnmarshaler, _TimeSheetRequest_OneofSizer, []interface{}{
		(*TimeSheetRequest_Email)(nil),
		(*TimeSheetRequest_UserID)(nil),
	}
}

func _TimeSheetRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TimeSheetRequest)
	// UserIdent
	switch x := m.UserIdent.(type) {
	case *TimeSheetRequest_Email:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Email)
	case *TimeSheetRequest_UserID:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.UserID))
	case nil:
	default:
		return fmt.Errorf("TimeSheetRequest.UserIdent has unexpected type %T", x)
	}
	return nil
}

func _TimeSheetRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TimeSheetRequest)
	switch tag {
	case 4: // UserIdent.Email
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.UserIdent = &TimeSheetRequest_Email{x}
		return true, err
	case 5: // UserIdent.UserID
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.UserIdent = &TimeSheetRequest_UserID{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _TimeSheetRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TimeSheetRequest)
	// UserIdent
	switch x := m.UserIdent.(type) {
	case *TimeSheetRequest_Email:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Email)))
		n += len(x.Email)
	case *TimeSheetRequest_UserID:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.UserID))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TSStatusResponse struct {
	State      TSStatusResponse_Status    `protobuf:"varint,1,opt,name=State,enum=api.TSStatusResponse_Status" json:"State,omitempty"`
	Timestamp  *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	LastWorked *google_protobuf1.Duration `protobuf:"bytes,3,opt,name=LastWorked" json:"LastWorked,omitempty"`
}

func (m *TSStatusResponse) Reset()                    { *m = TSStatusResponse{} }
func (m *TSStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*TSStatusResponse) ProtoMessage()               {}
func (*TSStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TSStatusResponse) GetState() TSStatusResponse_Status {
	if m != nil {
		return m.State
	}
	return TSStatusResponse_ClockedOut
}

func (m *TSStatusResponse) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TSStatusResponse) GetLastWorked() *google_protobuf1.Duration {
	if m != nil {
		return m.LastWorked
	}
	return nil
}

type TimeEntry struct {
	ID        int64                      `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	UserID    string                     `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=Timestamp" json:"Timestamp,omitempty"`
	State     TimeEntry_Status           `protobuf:"varint,4,opt,name=State,enum=api.TimeEntry_Status" json:"State,omitempty"`
}

func (m *TimeEntry) Reset()                    { *m = TimeEntry{} }
func (m *TimeEntry) String() string            { return proto.CompactTextString(m) }
func (*TimeEntry) ProtoMessage()               {}
func (*TimeEntry) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *TimeEntry) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TimeEntry) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TimeEntry) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TimeEntry) GetState() TimeEntry_Status {
	if m != nil {
		return m.State
	}
	return TimeEntry_ClockedOut
}

func init() {
	proto.RegisterType((*ClockRequest)(nil), "api.ClockRequest")
	proto.RegisterType((*TimeSheetRequest)(nil), "api.TimeSheetRequest")
	proto.RegisterType((*TSStatusResponse)(nil), "api.TSStatusResponse")
	proto.RegisterType((*TimeEntry)(nil), "api.TimeEntry")
	proto.RegisterEnum("api.TSStatusResponse_Status", TSStatusResponse_Status_name, TSStatusResponse_Status_value)
	proto.RegisterEnum("api.TimeEntry_Status", TimeEntry_Status_name, TimeEntry_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TimeSheet service

type TimeSheetClient interface {
	ClockIn(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ClockOut(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	GetCurrentStatus(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*TSStatusResponse, error)
	GetEntries(ctx context.Context, in *TimeSheetRequest, opts ...grpc.CallOption) (TimeSheet_GetEntriesClient, error)
}

type timeSheetClient struct {
	cc *grpc.ClientConn
}

func NewTimeSheetClient(cc *grpc.ClientConn) TimeSheetClient {
	return &timeSheetClient{cc}
}

func (c *timeSheetClient) ClockIn(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := grpc.Invoke(ctx, "/api.TimeSheet/ClockIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSheetClient) ClockOut(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := grpc.Invoke(ctx, "/api.TimeSheet/ClockOut", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSheetClient) GetCurrentStatus(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*TSStatusResponse, error) {
	out := new(TSStatusResponse)
	err := grpc.Invoke(ctx, "/api.TimeSheet/GetCurrentStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSheetClient) GetEntries(ctx context.Context, in *TimeSheetRequest, opts ...grpc.CallOption) (TimeSheet_GetEntriesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TimeSheet_serviceDesc.Streams[0], c.cc, "/api.TimeSheet/GetEntries", opts...)
	if err != nil {
		return nil, err
	}
	x := &timeSheetGetEntriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TimeSheet_GetEntriesClient interface {
	Recv() (*TimeEntry, error)
	grpc.ClientStream
}

type timeSheetGetEntriesClient struct {
	grpc.ClientStream
}

func (x *timeSheetGetEntriesClient) Recv() (*TimeEntry, error) {
	m := new(TimeEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TimeSheet service

type TimeSheetServer interface {
	ClockIn(context.Context, *ClockRequest) (*SimpleResponse, error)
	ClockOut(context.Context, *ClockRequest) (*SimpleResponse, error)
	GetCurrentStatus(context.Context, *ClockRequest) (*TSStatusResponse, error)
	GetEntries(*TimeSheetRequest, TimeSheet_GetEntriesServer) error
}

func RegisterTimeSheetServer(s *grpc.Server, srv TimeSheetServer) {
	s.RegisterService(&_TimeSheet_serviceDesc, srv)
}

func _TimeSheet_ClockIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSheetServer).ClockIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TimeSheet/ClockIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSheetServer).ClockIn(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSheet_ClockOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSheetServer).ClockOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TimeSheet/ClockOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSheetServer).ClockOut(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSheet_GetCurrentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSheetServer).GetCurrentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TimeSheet/GetCurrentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSheetServer).GetCurrentStatus(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSheet_GetEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TimeSheetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimeSheetServer).GetEntries(m, &timeSheetGetEntriesServer{stream})
}

type TimeSheet_GetEntriesServer interface {
	Send(*TimeEntry) error
	grpc.ServerStream
}

type timeSheetGetEntriesServer struct {
	grpc.ServerStream
}

func (x *timeSheetGetEntriesServer) Send(m *TimeEntry) error {
	return x.ServerStream.SendMsg(m)
}

var _TimeSheet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TimeSheet",
	HandlerType: (*TimeSheetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClockIn",
			Handler:    _TimeSheet_ClockIn_Handler,
		},
		{
			MethodName: "ClockOut",
			Handler:    _TimeSheet_ClockOut_Handler,
		},
		{
			MethodName: "GetCurrentStatus",
			Handler:    _TimeSheet_GetCurrentStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEntries",
			Handler:       _TimeSheet_GetEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "timesheet.proto",
}

func init() { proto.RegisterFile("timesheet.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0x26, 0xc1, 0xd3, 0x62, 0xc2, 0xa2, 0x56, 0xc6, 0x42, 0x10, 0xf9, 0x42, 0x24,
	0x90, 0x0b, 0x01, 0x24, 0x90, 0x38, 0xd1, 0x44, 0xad, 0x25, 0xa4, 0x48, 0x76, 0x11, 0xe7, 0x6d,
	0x3c, 0xb4, 0x56, 0x63, 0xaf, 0xd9, 0x1d, 0x1f, 0xf8, 0x3e, 0x7e, 0x05, 0x89, 0x23, 0xbf, 0x80,
	0xbc, 0x5e, 0xa7, 0x49, 0x89, 0x44, 0x7a, 0xdb, 0xd9, 0x7d, 0x6f, 0xfc, 0xde, 0x9b, 0x31, 0x3c,
	0xa0, 0x2c, 0x47, 0x75, 0x85, 0x48, 0x61, 0x29, 0x05, 0x09, 0x66, 0xf3, 0x32, 0xf3, 0x0f, 0x16,
	0x22, 0xcf, 0x45, 0xd1, 0x5c, 0xf9, 0xcf, 0x2e, 0x85, 0xb8, 0x5c, 0xe2, 0xb1, 0xae, 0x2e, 0xaa,
	0x6f, 0xc7, 0x9a, 0x43, 0x3c, 0x2f, 0x0d, 0xe0, 0xe9, 0x6d, 0x40, 0x5a, 0x49, 0x4e, 0x59, 0xdb,
	0x20, 0x70, 0xe1, 0xe0, 0x64, 0x29, 0x16, 0xd7, 0x31, 0x7e, 0xaf, 0x50, 0x51, 0xf0, 0xc7, 0x82,
	0xe1, 0x79, 0x96, 0x63, 0x52, 0x7f, 0xd7, 0x5c, 0xb2, 0x97, 0x30, 0x98, 0x97, 0x35, 0x49, 0x79,
	0xd6, 0xc8, 0x1a, 0xef, 0x4f, 0x58, 0xc8, 0xcb, 0x2c, 0x4c, 0x90, 0xcb, 0xc5, 0x95, 0x79, 0x89,
	0x5b, 0x08, 0x7b, 0x0f, 0x4e, 0x42, 0x5c, 0x52, 0xdd, 0xc6, 0xeb, 0x6a, 0xbc, 0x1f, 0x36, 0x32,
	0xc2, 0x56, 0x46, 0x78, 0xde, 0xea, 0x8c, 0x6f, 0xc0, 0xec, 0x2d, 0x0c, 0x66, 0x45, 0xaa, 0x79,
	0xf6, 0x7f, 0x79, 0x2d, 0x94, 0x1d, 0x41, 0x6f, 0x96, 0xf3, 0x6c, 0xe9, 0xed, 0x8d, 0xac, 0xb1,
	0x73, 0xd6, 0x89, 0x9b, 0x92, 0x79, 0xd0, 0xff, 0xa2, 0x50, 0x46, 0x53, 0xaf, 0x37, 0xb2, 0xc6,
	0xf6, 0x59, 0x27, 0x36, 0xf5, 0xa7, 0x7d, 0x70, 0xf4, 0x29, 0xc5, 0x82, 0x82, 0x5f, 0xb5, 0xe3,
	0x24, 0x21, 0x4e, 0x95, 0x8a, 0x51, 0x95, 0xa2, 0x50, 0xc8, 0x26, 0xd0, 0xab, 0x6f, 0x50, 0xfb,
	0x75, 0x27, 0x4f, 0xb4, 0xdf, 0xdb, 0xa8, 0xd0, 0x94, 0x0d, 0xb4, 0xf6, 0xbd, 0x52, 0xb7, 0x8b,
	0xef, 0xd5, 0x91, 0x7d, 0x00, 0xf8, 0xcc, 0x15, 0x7d, 0x15, 0xf2, 0x1a, 0x53, 0x63, 0xfd, 0xf1,
	0x3f, 0xd4, 0xa9, 0x99, 0x5c, 0xbc, 0x06, 0x0e, 0x9e, 0x43, 0xbf, 0x51, 0xc1, 0x5c, 0x00, 0x3d,
	0x49, 0x4c, 0xe7, 0x15, 0x0d, 0x3b, 0xec, 0x3e, 0x38, 0xa6, 0x8e, 0x8a, 0xa1, 0x15, 0xfc, 0xb4,
	0x1a, 0x79, 0xb3, 0x82, 0xe4, 0x0f, 0xe6, 0x42, 0x37, 0x9a, 0x6a, 0x73, 0x76, 0xdc, 0x8d, 0xa6,
	0xec, 0x68, 0x95, 0x55, 0x2d, 0xdc, 0x69, 0x93, 0xda, 0xf4, 0x64, 0xdf, 0xc5, 0xd3, 0x8b, 0x36,
	0xc1, 0x3d, 0x9d, 0xe0, 0x61, 0x93, 0x60, 0x2b, 0x60, 0x33, 0xba, 0x9d, 0x5d, 0x4c, 0x7e, 0x1b,
	0x17, 0x7a, 0x3d, 0xd9, 0x6b, 0x18, 0xe8, 0xc7, 0xa8, 0x60, 0x0f, 0x75, 0xff, 0xf5, 0x55, 0xf6,
	0x1f, 0x35, 0x4b, 0x9a, 0xe5, 0xe5, 0x12, 0xd7, 0x06, 0x7b, 0x4f, 0x83, 0xe6, 0x15, 0xed, 0xcc,
	0xf9, 0x08, 0xc3, 0x53, 0xa4, 0x93, 0x4a, 0x4a, 0x2c, 0xc8, 0xe8, 0xdc, 0xc2, 0x3d, 0xdc, 0xba,
	0x24, 0xec, 0x1d, 0xc0, 0x29, 0x52, 0xed, 0x3a, 0x43, 0xc5, 0x6e, 0x72, 0x58, 0xff, 0xc3, 0x7c,
	0x77, 0x33, 0x9e, 0x57, 0xd6, 0x45, 0x5f, 0xc7, 0xfb, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9b, 0x16, 0xf4, 0x2f, 0x06, 0x04, 0x00, 0x00,
}
