// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: timesheet.proto

package api

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TSStatusResponse_Status int32

const (
	TSStatusResponse_ClockedOut TSStatusResponse_Status = 0
	TSStatusResponse_ClockedIn  TSStatusResponse_Status = 1
)

var TSStatusResponse_Status_name = map[int32]string{
	0: "ClockedOut",
	1: "ClockedIn",
}
var TSStatusResponse_Status_value = map[string]int32{
	"ClockedOut": 0,
	"ClockedIn":  1,
}

func (x TSStatusResponse_Status) String() string {
	return proto.EnumName(TSStatusResponse_Status_name, int32(x))
}
func (TSStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTimesheet, []int{2, 0}
}

type TimeEntry_Status int32

const (
	TimeEntry_ClockedOut TimeEntry_Status = 0
	TimeEntry_ClockedIn  TimeEntry_Status = 1
)

var TimeEntry_Status_name = map[int32]string{
	0: "ClockedOut",
	1: "ClockedIn",
}
var TimeEntry_Status_value = map[string]int32{
	"ClockedOut": 0,
	"ClockedIn":  1,
}

func (x TimeEntry_Status) String() string {
	return proto.EnumName(TimeEntry_Status_name, int32(x))
}
func (TimeEntry_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorTimesheet, []int{3, 0} }

type ClockRequest struct {
}

func (m *ClockRequest) Reset()                    { *m = ClockRequest{} }
func (m *ClockRequest) String() string            { return proto.CompactTextString(m) }
func (*ClockRequest) ProtoMessage()               {}
func (*ClockRequest) Descriptor() ([]byte, []int) { return fileDescriptorTimesheet, []int{0} }

type TimeSheetRequest struct {
	Options   *SearchOptions             `protobuf:"bytes,1,opt,name=Options" json:"Options,omitempty"`
	StartTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime   *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=EndTime" json:"EndTime,omitempty"`
	// Types that are valid to be assigned to UserIdent:
	//	*TimeSheetRequest_Email
	//	*TimeSheetRequest_UserID
	UserIdent isTimeSheetRequest_UserIdent `protobuf_oneof:"UserIdent"`
}

func (m *TimeSheetRequest) Reset()                    { *m = TimeSheetRequest{} }
func (m *TimeSheetRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeSheetRequest) ProtoMessage()               {}
func (*TimeSheetRequest) Descriptor() ([]byte, []int) { return fileDescriptorTimesheet, []int{1} }

type isTimeSheetRequest_UserIdent interface {
	isTimeSheetRequest_UserIdent()
	MarshalTo([]byte) (int, error)
	Size() int
}

type TimeSheetRequest_Email struct {
	Email string `protobuf:"bytes,4,opt,name=Email,proto3,oneof"`
}
type TimeSheetRequest_UserID struct {
	UserID int64 `protobuf:"varint,5,opt,name=UserID,proto3,oneof"`
}

func (*TimeSheetRequest_Email) isTimeSheetRequest_UserIdent()  {}
func (*TimeSheetRequest_UserID) isTimeSheetRequest_UserIdent() {}

func (m *TimeSheetRequest) GetUserIdent() isTimeSheetRequest_UserIdent {
	if m != nil {
		return m.UserIdent
	}
	return nil
}

func (m *TimeSheetRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *TimeSheetRequest) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TimeSheetRequest) GetEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TimeSheetRequest) GetEmail() string {
	if x, ok := m.GetUserIdent().(*TimeSheetRequest_Email); ok {
		return x.Email
	}
	return ""
}

func (m *TimeSheetRequest) GetUserID() int64 {
	if x, ok := m.GetUserIdent().(*TimeSheetRequest_UserID); ok {
		return x.UserID
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TimeSheetRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TimeSheetRequest_OneofMarshaler, _TimeSheetRequest_OneofUnmarshaler, _TimeSheetRequest_OneofSizer, []interface{}{
		(*TimeSheetRequest_Email)(nil),
		(*TimeSheetRequest_UserID)(nil),
	}
}

func _TimeSheetRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TimeSheetRequest)
	// UserIdent
	switch x := m.UserIdent.(type) {
	case *TimeSheetRequest_Email:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Email)
	case *TimeSheetRequest_UserID:
		_ = b.EncodeVarint(5<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.UserID))
	case nil:
	default:
		return fmt.Errorf("TimeSheetRequest.UserIdent has unexpected type %T", x)
	}
	return nil
}

func _TimeSheetRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TimeSheetRequest)
	switch tag {
	case 4: // UserIdent.Email
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.UserIdent = &TimeSheetRequest_Email{x}
		return true, err
	case 5: // UserIdent.UserID
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.UserIdent = &TimeSheetRequest_UserID{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _TimeSheetRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TimeSheetRequest)
	// UserIdent
	switch x := m.UserIdent.(type) {
	case *TimeSheetRequest_Email:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Email)))
		n += len(x.Email)
	case *TimeSheetRequest_UserID:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.UserID))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TSStatusResponse struct {
	State      TSStatusResponse_Status    `protobuf:"varint,1,opt,name=State,proto3,enum=api.TSStatusResponse_Status" json:"State,omitempty"`
	Timestamp  *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	LastWorked *google_protobuf1.Duration `protobuf:"bytes,3,opt,name=LastWorked" json:"LastWorked,omitempty"`
}

func (m *TSStatusResponse) Reset()                    { *m = TSStatusResponse{} }
func (m *TSStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*TSStatusResponse) ProtoMessage()               {}
func (*TSStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptorTimesheet, []int{2} }

func (m *TSStatusResponse) GetState() TSStatusResponse_Status {
	if m != nil {
		return m.State
	}
	return TSStatusResponse_ClockedOut
}

func (m *TSStatusResponse) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TSStatusResponse) GetLastWorked() *google_protobuf1.Duration {
	if m != nil {
		return m.LastWorked
	}
	return nil
}

type TimeEntry struct {
	ID        int64                      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID    string                     `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=Timestamp" json:"Timestamp,omitempty"`
	State     TimeEntry_Status           `protobuf:"varint,4,opt,name=State,proto3,enum=api.TimeEntry_Status" json:"State,omitempty"`
}

func (m *TimeEntry) Reset()                    { *m = TimeEntry{} }
func (m *TimeEntry) String() string            { return proto.CompactTextString(m) }
func (*TimeEntry) ProtoMessage()               {}
func (*TimeEntry) Descriptor() ([]byte, []int) { return fileDescriptorTimesheet, []int{3} }

func (m *TimeEntry) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TimeEntry) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TimeEntry) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TimeEntry) GetState() TimeEntry_Status {
	if m != nil {
		return m.State
	}
	return TimeEntry_ClockedOut
}

func init() {
	proto.RegisterType((*ClockRequest)(nil), "api.ClockRequest")
	proto.RegisterType((*TimeSheetRequest)(nil), "api.TimeSheetRequest")
	proto.RegisterType((*TSStatusResponse)(nil), "api.TSStatusResponse")
	proto.RegisterType((*TimeEntry)(nil), "api.TimeEntry")
	proto.RegisterEnum("api.TSStatusResponse_Status", TSStatusResponse_Status_name, TSStatusResponse_Status_value)
	proto.RegisterEnum("api.TimeEntry_Status", TimeEntry_Status_name, TimeEntry_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TimeSheet service

type TimeSheetClient interface {
	ClockIn(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ClockOut(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	GetCurrentStatus(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*TSStatusResponse, error)
	GetEntries(ctx context.Context, in *TimeSheetRequest, opts ...grpc.CallOption) (TimeSheet_GetEntriesClient, error)
}

type timeSheetClient struct {
	cc *grpc.ClientConn
}

func NewTimeSheetClient(cc *grpc.ClientConn) TimeSheetClient {
	return &timeSheetClient{cc}
}

func (c *timeSheetClient) ClockIn(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := grpc.Invoke(ctx, "/api.TimeSheet/ClockIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSheetClient) ClockOut(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := grpc.Invoke(ctx, "/api.TimeSheet/ClockOut", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSheetClient) GetCurrentStatus(ctx context.Context, in *ClockRequest, opts ...grpc.CallOption) (*TSStatusResponse, error) {
	out := new(TSStatusResponse)
	err := grpc.Invoke(ctx, "/api.TimeSheet/GetCurrentStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSheetClient) GetEntries(ctx context.Context, in *TimeSheetRequest, opts ...grpc.CallOption) (TimeSheet_GetEntriesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TimeSheet_serviceDesc.Streams[0], c.cc, "/api.TimeSheet/GetEntries", opts...)
	if err != nil {
		return nil, err
	}
	x := &timeSheetGetEntriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TimeSheet_GetEntriesClient interface {
	Recv() (*TimeEntry, error)
	grpc.ClientStream
}

type timeSheetGetEntriesClient struct {
	grpc.ClientStream
}

func (x *timeSheetGetEntriesClient) Recv() (*TimeEntry, error) {
	m := new(TimeEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TimeSheet service

type TimeSheetServer interface {
	ClockIn(context.Context, *ClockRequest) (*SimpleResponse, error)
	ClockOut(context.Context, *ClockRequest) (*SimpleResponse, error)
	GetCurrentStatus(context.Context, *ClockRequest) (*TSStatusResponse, error)
	GetEntries(*TimeSheetRequest, TimeSheet_GetEntriesServer) error
}

func RegisterTimeSheetServer(s *grpc.Server, srv TimeSheetServer) {
	s.RegisterService(&_TimeSheet_serviceDesc, srv)
}

func _TimeSheet_ClockIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSheetServer).ClockIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TimeSheet/ClockIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSheetServer).ClockIn(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSheet_ClockOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSheetServer).ClockOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TimeSheet/ClockOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSheetServer).ClockOut(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSheet_GetCurrentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSheetServer).GetCurrentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TimeSheet/GetCurrentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSheetServer).GetCurrentStatus(ctx, req.(*ClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSheet_GetEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TimeSheetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimeSheetServer).GetEntries(m, &timeSheetGetEntriesServer{stream})
}

type TimeSheet_GetEntriesServer interface {
	Send(*TimeEntry) error
	grpc.ServerStream
}

type timeSheetGetEntriesServer struct {
	grpc.ServerStream
}

func (x *timeSheetGetEntriesServer) Send(m *TimeEntry) error {
	return x.ServerStream.SendMsg(m)
}

var _TimeSheet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TimeSheet",
	HandlerType: (*TimeSheetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClockIn",
			Handler:    _TimeSheet_ClockIn_Handler,
		},
		{
			MethodName: "ClockOut",
			Handler:    _TimeSheet_ClockOut_Handler,
		},
		{
			MethodName: "GetCurrentStatus",
			Handler:    _TimeSheet_GetCurrentStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEntries",
			Handler:       _TimeSheet_GetEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "timesheet.proto",
}

func (m *ClockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClockRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *TimeSheetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TimeSheetRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Options != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.Options.Size()))
		n1, err := m.Options.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.StartTime != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.StartTime.Size()))
		n2, err := m.StartTime.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.EndTime != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.EndTime.Size()))
		n3, err := m.EndTime.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.UserIdent != nil {
		nn4, err := m.UserIdent.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn4
	}
	return i, nil
}

func (m *TimeSheetRequest_Email) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	dAtA[i] = 0x22
	i++
	i = encodeVarintTimesheet(dAtA, i, uint64(len(m.Email)))
	i += copy(dAtA[i:], m.Email)
	return i, nil
}
func (m *TimeSheetRequest_UserID) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	dAtA[i] = 0x28
	i++
	i = encodeVarintTimesheet(dAtA, i, uint64(m.UserID))
	return i, nil
}
func (m *TSStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TSStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.State))
	}
	if m.Timestamp != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.Timestamp.Size()))
		n5, err := m.Timestamp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.LastWorked != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.LastWorked.Size()))
		n6, err := m.LastWorked.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}

func (m *TimeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TimeEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.ID))
	}
	if len(m.UserID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(len(m.UserID)))
		i += copy(dAtA[i:], m.UserID)
	}
	if m.Timestamp != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.Timestamp.Size()))
		n7, err := m.Timestamp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if m.State != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTimesheet(dAtA, i, uint64(m.State))
	}
	return i, nil
}

func encodeVarintTimesheet(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClockRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *TimeSheetRequest) Size() (n int) {
	var l int
	_ = l
	if m.Options != nil {
		l = m.Options.Size()
		n += 1 + l + sovTimesheet(uint64(l))
	}
	if m.StartTime != nil {
		l = m.StartTime.Size()
		n += 1 + l + sovTimesheet(uint64(l))
	}
	if m.EndTime != nil {
		l = m.EndTime.Size()
		n += 1 + l + sovTimesheet(uint64(l))
	}
	if m.UserIdent != nil {
		n += m.UserIdent.Size()
	}
	return n
}

func (m *TimeSheetRequest_Email) Size() (n int) {
	var l int
	_ = l
	l = len(m.Email)
	n += 1 + l + sovTimesheet(uint64(l))
	return n
}
func (m *TimeSheetRequest_UserID) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovTimesheet(uint64(m.UserID))
	return n
}
func (m *TSStatusResponse) Size() (n int) {
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovTimesheet(uint64(m.State))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.Size()
		n += 1 + l + sovTimesheet(uint64(l))
	}
	if m.LastWorked != nil {
		l = m.LastWorked.Size()
		n += 1 + l + sovTimesheet(uint64(l))
	}
	return n
}

func (m *TimeEntry) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovTimesheet(uint64(m.ID))
	}
	l = len(m.UserID)
	if l > 0 {
		n += 1 + l + sovTimesheet(uint64(l))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.Size()
		n += 1 + l + sovTimesheet(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovTimesheet(uint64(m.State))
	}
	return n
}

func sovTimesheet(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTimesheet(x uint64) (n int) {
	return sovTimesheet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTimesheet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTimesheet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTimesheet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TimeSheetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTimesheet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TimeSheetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TimeSheetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Options", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Options == nil {
				m.Options = &SearchOptions{}
			}
			if err := m.Options.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartTime == nil {
				m.StartTime = &google_protobuf.Timestamp{}
			}
			if err := m.StartTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = &google_protobuf.Timestamp{}
			}
			if err := m.EndTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserIdent = &TimeSheetRequest_Email{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UserIdent = &TimeSheetRequest_UserID{v}
		default:
			iNdEx = preIndex
			skippy, err := skipTimesheet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTimesheet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TSStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTimesheet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TSStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TSStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= (TSStatusResponse_Status(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &google_protobuf.Timestamp{}
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastWorked", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastWorked == nil {
				m.LastWorked = &google_protobuf1.Duration{}
			}
			if err := m.LastWorked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTimesheet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTimesheet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TimeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTimesheet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TimeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TimeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTimesheet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &google_protobuf.Timestamp{}
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= (TimeEntry_Status(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTimesheet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTimesheet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTimesheet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTimesheet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTimesheet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTimesheet
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTimesheet
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTimesheet(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTimesheet = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTimesheet   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("timesheet.proto", fileDescriptorTimesheet) }

var fileDescriptorTimesheet = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0xd6, 0x4d, 0x82, 0xa7, 0xc5, 0x98, 0x45, 0xad, 0x8c, 0x85, 0x4c, 0xe4, 0x0b, 0x91,
	0x40, 0x2e, 0x04, 0x90, 0x40, 0xe2, 0xd4, 0x26, 0x6a, 0x2d, 0x21, 0x45, 0xb2, 0x8b, 0x38, 0xbb,
	0xf1, 0xd0, 0x5a, 0x8d, 0x3f, 0xf0, 0x8e, 0x0f, 0xfc, 0x0b, 0xfe, 0x13, 0x17, 0x8e, 0xfc, 0x04,
	0x14, 0x90, 0x38, 0xf2, 0x17, 0x90, 0xd7, 0xeb, 0x34, 0x29, 0x95, 0x08, 0xb7, 0x9d, 0xdd, 0xf7,
	0xc6, 0xef, 0xbd, 0x19, 0xc3, 0x1d, 0x4a, 0x52, 0x14, 0x17, 0x88, 0xe4, 0x15, 0x65, 0x4e, 0x39,
	0xd7, 0xa2, 0x22, 0xb1, 0x77, 0x67, 0x79, 0x9a, 0xe6, 0x59, 0x73, 0x65, 0x3f, 0x3c, 0xcf, 0xf3,
	0xf3, 0x39, 0x1e, 0xc8, 0xea, 0xac, 0xfa, 0x70, 0x20, 0x39, 0x14, 0xa5, 0x85, 0x02, 0x38, 0xd7,
	0x01, 0x71, 0x55, 0x46, 0x94, 0xb4, 0x0d, 0x5c, 0x03, 0x76, 0x8f, 0xe6, 0xf9, 0xec, 0x32, 0xc0,
	0x8f, 0x15, 0x0a, 0x72, 0x7f, 0x33, 0x30, 0x4f, 0x93, 0x14, 0xc3, 0xfa, 0xbb, 0xea, 0x92, 0x3f,
	0x81, 0xfe, 0xb4, 0xa8, 0x49, 0xc2, 0x62, 0x03, 0x36, 0xdc, 0x19, 0x71, 0x2f, 0x2a, 0x12, 0x2f,
	0xc4, 0xa8, 0x9c, 0x5d, 0xa8, 0x97, 0xa0, 0x85, 0xf0, 0x57, 0xa0, 0x87, 0x14, 0x95, 0x54, 0xb7,
	0xb1, 0xb6, 0x24, 0xde, 0xf6, 0x1a, 0x19, 0x5e, 0x2b, 0xc3, 0x3b, 0x6d, 0x75, 0x06, 0x57, 0x60,
	0xfe, 0x02, 0xfa, 0x93, 0x2c, 0x96, 0x3c, 0xed, 0x9f, 0xbc, 0x16, 0xca, 0xf7, 0xa1, 0x3b, 0x49,
	0xa3, 0x64, 0x6e, 0x6d, 0x0f, 0xd8, 0x50, 0x3f, 0xe9, 0x04, 0x4d, 0xc9, 0x2d, 0xe8, 0xbd, 0x13,
	0x58, 0xfa, 0x63, 0xab, 0x3b, 0x60, 0x43, 0xed, 0xa4, 0x13, 0xa8, 0xfa, 0x70, 0x07, 0x74, 0x79,
	0x8a, 0x31, 0x23, 0xf7, 0x67, 0xed, 0x38, 0x0c, 0x29, 0xa2, 0x4a, 0x04, 0x28, 0x8a, 0x3c, 0x13,
	0xc8, 0x47, 0xd0, 0xad, 0x6f, 0x50, 0xfa, 0x35, 0x46, 0x0f, 0xa4, 0xdf, 0xeb, 0x28, 0x4f, 0x95,
	0x0d, 0xb4, 0xf6, 0xbd, 0x54, 0xb7, 0x89, 0xef, 0xe5, 0x91, 0xbf, 0x06, 0x78, 0x1b, 0x09, 0x7a,
	0x9f, 0x97, 0x97, 0x18, 0x2b, 0xeb, 0xf7, 0xff, 0xa2, 0x8e, 0xd5, 0xe4, 0x82, 0x15, 0xb0, 0xfb,
	0x08, 0x7a, 0x8d, 0x0a, 0x6e, 0x00, 0xc8, 0x49, 0x62, 0x3c, 0xad, 0xc8, 0xec, 0xf0, 0xdb, 0xa0,
	0xab, 0xda, 0xcf, 0x4c, 0xe6, 0x7e, 0x61, 0x8d, 0xbc, 0x49, 0x46, 0xe5, 0x27, 0x6e, 0xc0, 0x96,
	0x3f, 0x96, 0xe6, 0xb4, 0x60, 0xcb, 0x1f, 0xf3, 0xfd, 0x65, 0x56, 0xb5, 0x70, 0xbd, 0x4d, 0x6a,
	0xdd, 0x93, 0xf6, 0x3f, 0x9e, 0x1e, 0xb7, 0x09, 0x6e, 0xcb, 0x04, 0xf7, 0x9a, 0x04, 0x5b, 0x01,
	0xeb, 0xd1, 0x6d, 0xec, 0x62, 0xf4, 0x4b, 0xb9, 0x90, 0xeb, 0xc9, 0x9f, 0x41, 0x5f, 0x3e, 0xfa,
	0x19, 0xbf, 0x2b, 0xfb, 0xaf, 0xae, 0xb2, 0x7d, 0xaf, 0x59, 0xd2, 0x24, 0x2d, 0xe6, 0xb8, 0x32,
	0xd8, 0x5b, 0x12, 0x34, 0xad, 0x68, 0x63, 0xce, 0x1b, 0x30, 0x8f, 0x91, 0x8e, 0xaa, 0xb2, 0xc4,
	0x8c, 0x94, 0xce, 0x1b, 0xb8, 0x7b, 0x37, 0x2e, 0x09, 0x7f, 0x09, 0x70, 0x8c, 0x54, 0xbb, 0x4e,
	0x50, 0xf0, 0xab, 0x1c, 0x56, 0xff, 0x30, 0xdb, 0x58, 0x8f, 0xe7, 0x29, 0x3b, 0x34, 0xbf, 0x2e,
	0x1c, 0xf6, 0x6d, 0xe1, 0xb0, 0xef, 0x0b, 0x87, 0x7d, 0xfe, 0xe1, 0x74, 0xce, 0x7a, 0x32, 0xf0,
	0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x5c, 0x20, 0xd0, 0x18, 0x04, 0x00, 0x00,
}
