
SQL:
    Driver: mysql
    Connection: gotime:^5pXweFk9Q8ZVXu7!yOv@127.0.0.1:3306/gotime
Session:
	Secret: somes3cr3t
	Options:
		Path: /
		Domain: gotime.shambhalamountain.org
		MaxAge: 2592000
		Secure: true
		HttpOnly: false
